// Workshop/10 - Svelte/kanye-rest/src/lib/Button.svelte

<script>

</script>

<button on:click>
    <slot/>
</button>

<style>
    button {
        background-color: #ffffff;
        border: none;
        color: black;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
    }
</style>

// React/05/src/component/Button/index.js
import React from "react";
import PropTypes from "prop-types";
import styled from "styled-components";

const StyledButton = styled.button`
    background-color: ${props => props.backgroundColor};
  filter: ${props => props.inverted ? "invert(100%)" : "none"};
    color: ${props => props.color};
    border: none;
    border-radius: 5px;
    padding: 10px;
    font-size: 16px;
    cursor: pointer;
    &:hover {
        background-color: ${props => props.hoverBackgroundColor};
        color: ${props => props.hoverColor};
    }
`;

const Button = (props) => {
    return (
        <StyledButton className="btn" onClick={props.click} style={props.style} inverted={props.inverted} backgroundColor={props.backgroundColor} color={props.color} hoverBackgroundColor={props.hoverBackgroundColor} hoverColor={props.hoverColor}>
            {props.buttonText}
        </StyledButton>
    );
};

Button.propTypes = {
    buttonText: PropTypes.string,
    click: PropTypes.func,
};

export default Button;
